# Generated by Django 3.1.2 on 2020-11-11 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Surya_Pizzeria', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin_Database',
        ),
    ]
