# Generated by Django 3.1.2 on 2020-11-11 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Surya_Pizzeria', '0002_delete_admin_database'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pizza_name', models.CharField(max_length=20)),
            ],
        ),
    ]
