# Generated by Django 3.1.2 on 2020-11-11 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Surya_Pizzeria', '0003_pizza_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza_data',
            name='pizza_name',
            field=models.CharField(max_length=50),
        ),
    ]
