# Generated by Django 3.1.2 on 2020-11-11 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Surya_Pizzeria', '0005_pizza_data_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza_data',
            name='price',
            field=models.CharField(max_length=10),
        ),
    ]
