# Generated by Django 3.1.2 on 2020-11-11 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Surya_Pizzeria', '0006_auto_20201111_1854'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizza_data',
            old_name='price',
            new_name='pizza_price',
        ),
    ]
